# Generated by Django 6.0.4 on 2026-05-15 00:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_caixa_conta_movimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('bandeira', models.IntegerField(choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'Elo'), (4, 'American Express')], default=1)),
                ('limite_consumo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('limite_maximo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('limite_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_investimento', models.IntegerField(choices=[(1, 'Ações'), (2, 'Fundos Imobiliários'), (3, 'Tesouro Direto'), (4, 'Criptomoedas')], default=1)),
                ('percentual_anual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='conta',
        ),
        migrations.AddField(
            model_name='movimento',
            name='desaconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimento',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Entrada'), (2, 'Saída')], default=1),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Conta_bancaria',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('conta', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='mov_investimento',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimento', models.IntegerField(choices=[(1, 'Credito'), (2, 'Debito')], default=1)),
                ('data_movimento', models.DateField(default=django.utils.timezone.now)),
                ('valor_movimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.investimento')),
            ],
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_movimento', models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa')], default=1)),
                ('data_vencimento', models.DateField(default=django.utils.timezone.now)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('juros', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulos_cartao', to='Core.cartao')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.conta_bancaria')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.perfil')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.tipo')),
            ],
        ),
        migrations.AddField(
            model_name='movimento',
            name='id_titulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.titulos'),
        ),
        migrations.DeleteModel(
            name='Conta',
        ),
    ]
