# Generated by Django 6.0.4 on 2026-05-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_remove_titulos_perfil_perfil_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nome',
        ),
        migrations.AddField(
            model_name='perfil',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'user')], default=2),
        ),
    ]
