# Generated by Django 6.0.4 on 2026-05-22 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_titulos_codigo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='titulos',
            old_name='tipo',
            new_name='Categoria',
        ),
    ]
