# Generated by Django 6.0.4 on 2026-05-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_cartao_id_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta_bancaria',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
