# Generated by Django 6.0.4 on 2026-06-10 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_conta_bancaria_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='perfil',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Core.perfil'),
            preserve_default=False,
        ),
    ]
