# Generated by Django 6.0.4 on 2026-06-10 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_categoria_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.perfil'),
            preserve_default=False,
        ),
    ]
